---
title: "Van Jackson"
date: 2020
output:
  html_document: default

---
## Education
- Fourth Year at University of California, Santa Barbara
- High school diploma

---

## Experience
- Took Comp Sci 8 as an intro to python
- Have used google Earth and Earth null for geographical studies
- Solid background in statistics for data analysis

# Resume
Van Jackson

Skills Summary
- Works well with others/extrovert		- Responsible		- Well organized
- Honest 			                        - Reliable	            - Positive attitude
- Hard worker				            - Committed/ Focused	                   		 - Energetic 					- Technology oriented  - Quick learner 	

Education
Villa Park High School
18042 E Taft Ave Villa Park, CA 92861
4.5 GPA 

University of California Santa Barbara
Completed first year, heading into second
Communications major
3.0 GPA


Volunteer Experience
- Apart of an organization called NLYM that focuses on giving back to the community by taking part in multiple philanthropies throughout the year.
- Working with my dad’s pit crew for his trophy lite truck.
- Volunteering for certain events at the Blind Children’s Learning Center: attending the annual 5k walk and raising over $5,000 each time.
- Occasionally help upkeep the warehouse at Budget Blinds by cleaning it out.
-Worked washing cars for a traveling company

Activities
-Freshman: Football, Basketball, Track
-Sophomore: Basketball
-Junior: Volleyball
-Senior: N/A
-Surfrider Foundation- Beach clean ups and surf sessions after
- President/founder of The Blind Children’s Learning center Club at my school. We focus on organizing events to spend time with the disabled kids.
- Fluent in English and took 5 years of Spanish. I would say I am at a proficient level in Spanish.

