---
title: "Projects"
---

In the summer of 2020 I took a class GIS course based in R. I wrote some code, and did some cool data science. Here is a collection of links! 

## [Building a project website]()  `r icon::fa("sun", color = "lime")`

- In this assignment we built a static users site with Github Pages 
- Includes a github repo for access to all the code.
- Look at how high quality my work is!

### [What I learned]()  `r icon::fa("sun", color = "lime")`
- How to input icons.
- How to adjust and create headers, titles, and bulletted lists
- How to bring in files from finder i.e. images into the img directory
- How to basically build a website on github!

---

#Lab 2
[Lab 02: Covid](https://van-jackson.github.io/geog-176A-labs/lab-02.html)
- This lab consisted of data wrangling and visualization skills using real-time COVID-19 data maintained by the New York Times. 
- Emphasis is placed on data.frame manipulation, and joining datasets.

---


#Lab 3
[Lab 03: Distances and Projections](https://van-jackson.github.io/geog-176A-labs/lab-03.html)
- This lab required me to replicate the ACLU assessment that 2/3 of the USA population lives within the 100 mile “Border Zone” where 4th ammendment rights are being questioned.
- I created a buffer zone showing different variations of data relating to borders.


---

#Lab 4
[Lab 04: Tesselations, Spatial Joins, and Point-in-Polygon](https://van-jackson.github.io/geog-176A-labs/lab-04.html)
- The National Dams Inventory was used to answer specific questions about geometry simplication, centroid generation, and tesselations. 
- I used my tesselations to explore the distribution of dams (and dam purpose) across the USA and challenges with the MAUP.


---

#Lab 5
[Lab 05: Raster Analysis](https://van-jackson.github.io/geog-176A-labs/lab-05.html)
- In this lab I worked with multiband raster files to detect and analyze a flood event near Palo, Iowa.
- I worked to complete the entire workflow from data aquisition through analysis in R and will see how the raster data structure allows us to draw meaningful conclusions from the data. 
- This kind of work goes on regularly and is part of a couple national efforts (NOAA, USGS, FirstStreet, FEMA) to generate flood inundation libraries that contribute to better extraction and classification of real-time flood events, resource allocation during events, and damage assessments post events.

---

#Lab 6
[Lab 06: Terrain Analysis](https://van-jackson.github.io/geog-176A-labs/lab-06.html)
- In this lab I estimated the number of buildings impacted in the 2017 Santa Barbara flood event along Mission Creek using data from web APIs (NLDI, OSM, AWS Elevation tiles). 
- I used the whitebox frontend to generate a Height Above Nearest Drainage layer for the Mission Creek watershed, and convert this layer into a Flood Inudation Map (FIM) Library complete with structural damage assessment.

---